/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AmountInput: typeof import('./src/components/mobile/AmountInput.vue')['default']
    ClassifyPicker: typeof import('./src/components/mobile/ClassifyPicker.vue')['default']
    DatePicker: typeof import('./src/components/mobile/DatePicker.vue')['default']
    MobilePage: typeof import('./src/components/mobile/MobilePage.vue')['default']
    PullRefreshList: typeof import('./src/components/mobile/PullRefreshList.vue')['default']
    RecordItem: typeof import('./src/components/mobile/RecordItem.vue')['default']
    ReDialog: typeof import('./src/components/ReDialog/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Src: typeof import('./src/components/ReText/src/index.vue')['default']
    SummaryCard: typeof import('./src/components/mobile/SummaryCard.vue')['default']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
  }
}

// For TSX support
declare global {
  const AmountInput: typeof import('./src/components/mobile/AmountInput.vue')['default']
  const ClassifyPicker: typeof import('./src/components/mobile/ClassifyPicker.vue')['default']
  const DatePicker: typeof import('./src/components/mobile/DatePicker.vue')['default']
  const MobilePage: typeof import('./src/components/mobile/MobilePage.vue')['default']
  const PullRefreshList: typeof import('./src/components/mobile/PullRefreshList.vue')['default']
  const RecordItem: typeof import('./src/components/mobile/RecordItem.vue')['default']
  const ReDialog: typeof import('./src/components/ReDialog/index.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const Src: typeof import('./src/components/ReText/src/index.vue')['default']
  const SummaryCard: typeof import('./src/components/mobile/SummaryCard.vue')['default']
  const VanNavBar: typeof import('vant/es')['NavBar']
  const VanTabbar: typeof import('vant/es')['Tabbar']
  const VanTabbarItem: typeof import('vant/es')['TabbarItem']
}